### ISSUE TITLE
Public pages in admin view ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/cheminfo.org#17]
It is not always easy to create a page from scratch. Would it be possible from the administrative view to allow the search engine in order to retrieve a view that could then be duplicate in your own name space ?

**Comment by stropitek** [comment]
We would need to create a new header I think (rather than adding something more to the couchdb button). You would first search and load via the research header, then save it in your namespace with the couchdb header.

**Comment by stropitek** [comment]
This is now possible
