### ISSUE TITLE
Layout problem when there is a description

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/cheminfo.org#30]
http://www.cheminfo.org/Spectra/NMR/Predictions/1H_Prediction.html?viewURL=http%3A%2F%2Fcouch.cheminfo.org%2Fcheminfo%2Feea0ba081ea2cc99da5c1aed2f29a0a8%2Fview.json%3Frev%3D38-67e37694187cb13c3456e1a28eb6209b&v=v2.17.5

**Comment by stropitek** [comment]
Fixed in cheminfo/flavor-builder@7835661a0abf6d4a364b0574a9aeccd1f803490b
