### ISSUE TITLE
virtual combinatorial library

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/cheminfo.org#32]
* change view title
* update to latest
* PC filter should update the downloadable files
* show the total number of molecules AND filtered number

**Comment by lpatiny** [comment]
clean the views (and keep large)

**Comment by lpatiny** [comment]
reference: http://pubs.rsc.org/en/content/articlehtml/2015/gc/c5gc01022e

**Comment by targos** [comment]
http://www.cheminfo.org/Chemistry/Cheminformatics/Virtual_combinatorial_library.html
