### ISSUE TITLE
Problem loading file in Firefox

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/cheminfo.org#33]
http://www.cheminfo.org/flavor/malaria/3D_models.html?viewURL=http%3A%2F%2Fcouch.cheminfo.org%2Fcheminfo%2Fe1f16b237a79ee04363ade8bce08a7d4%2Fview.json%3Frev%3D5-0ae4dd67637f955142f8cba665667b3b

We get an error in firefox with request OPTIONS that does not appear in Chrome. Any idea how to solve this ?

**Comment by targos** [comment]
I don't know why it works on Chrome but I think something is misconfigured in the proxy: 
![image](https://cloud.githubusercontent.com/assets/2352663/10506087/79430e3a-7314-11e5-923b-915ca9dbe6fa.png)
The redirect feels wrong, shouldn't it be followed by Apache instead of returned to the browser ?

**Comment by targos** [comment]
The problem was related to http to https proxypass that implied a redirection. It works correctly now
