### ISSUE TITLE
PCA crash ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/cheminfo.org#39]
https://my.cheminfo.org/?viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2F322d373f937cb95a6706334d60a2c544%2Fview.json&v=HEAD&direct=true

If you add with the from: 100, to: 1500 the data in attachment in crash (infinite loop). There is for sure some (a lot of) columns that contains only 0 but it would be better if there is no infinite loop

[Archive.zip](https://github.com/cheminfo/cheminfo.org/files/295003/Archive.zip)

**Comment by targos** [comment]
fixed in latest ml release

**Comment by targos** [comment]
the reason was that you cannot scale the data if there is a constant column because the standard deviation would be zero
