### ISSUE TITLE
Google not indexing well the website

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/cheminfo.org#41]
Googlebot see the pages as:

![image](https://cloud.githubusercontent.com/assets/1484241/15804154/6dbc11d8-2af7-11e6-89fd-c14e4b358709.png)

Meanings that no text is apparently indexed which is quite annoying.

The text is mainly in the postit as well rich text editor in the page. While there was the system of metatag in the view manager I think it is not the case anymore.
We should move to another system where:

1. During the build the system looks for rich text editor or post-it and retrieve the TEXT. We should try based on this to make a meta description of maximum 160 characters ...

2. Generate a body that would allow google to index the full content of the page. Meaning that the index.html page contains all the text from post-it and rich text editor that will then disappear when the visualizer loads. This can lead to bad flickering. We could therefore create static view that contains server side include code that will depends of the browser. If it is a robot we show all the text box as plain text, otherwise we just proceed as now. https://httpd.apache.org/docs/current/mod/mod_setenvif.html#browsermatchnocase

**Comment by targos** [comment]
you could also put transparent text. I suppose googlebot doesn't care about the color for indexing ?

**Comment by lpatiny** [comment]
Yes google should be smart enough to find out we try to cheat in this case. While in our case we just want to show the same information in an indexable way.
Here is an example code that we should use:
http://www.cheminfo.org/test.shtml
Should be relatively easy.

**Comment by lpatiny** [comment]
Concerning transparent text google has a page about it: https://support.google.com/webmasters/answer/66353?hl=en

**Comment by lpatiny** [comment]
All the pages have been indexed by google and we should take care to add more information in post-it in all our views.

Currently however the page does not look correctly in the browser. No css for the menu and the menu is after the content. @stropitek could you fix this ?

Don't know if you was using the plugin User-Agent Switcher to test but it works really well.
