### ISSUE TITLE
regression and r²

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/cheminfo.org#42]
It seems that we have a very high r² in the view:

https://my.cheminfo.org/?viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2F5aa6d6a775fd9ad46871d921b7e24a3e%2Fview.json&v=v2.56.0

Does not seem normal

![image](https://cloud.githubusercontent.com/assets/1484241/16058982/56e74680-3281-11e6-9edd-d2f48673ef4e.png)

**Comment by andcastillo** [comment]
It is the expected value. It measures the correlation, and both function are of the same kind. Perhaps we have to include the Mean Square Error to complement. That is more related to the differences between the curves.
